# Generated by Django 4.2.2 on 2023-06-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_storage',
            name='img_input',
            field=models.ImageField(null=True, upload_to='imgs/input'),
        ),
        migrations.AlterField(
            model_name='image_storage',
            name='img',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
    ]
